services:
  - type: web
    name: coman-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn mysite.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: coman-backend
          property: connectionString
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "False"
