# Generated by Django 5.0.7 on 2025-05-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_event_eventregister"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
